version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slark
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: slark