spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cabinet
    username: postgres
    password: slark343
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5432/cabinet
    user: postgres
    password: slark343
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 946a2edf6e5d8f7a35e7a00d1f853bc1cc622de06794f8d9adf833e76db1b7118e23b7
  access: 1800000
  refresh: 1296000000
server:
  port: 8080